jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: label-the-PR
      uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yml
        pr-number: ${{ github.event.inputs.oldPRs }}
name: Pull Request Labeler (manual)
on:
  repository_dispatch:
    types: trigger-ga___labeler-manual.yml
